### ISSUE TITLE
Ratatouille, most versions freeze before gameplay (regression)

### ISSUE THREAD

**Issue by TwoSpacesSG** [TASEmulators/freej2me-plus#17] opened 2024-10-06 10:08 UTC
High-end versions (see screenshot) freeze every time you press a key in the menu, meaning the game can't be played. Only exception to this seems to be the Russian Motorola 176x204 version.
![Screenshot from 2024-10-06 12-01-43](https://github.com/user-attachments/assets/f10d2d7d-291a-401a-bb0b-a316d19a851c)

Low-end versions freeze every time you start a new game. Only exception to this seems to be the Russian Nokia 128x160 version.
![Screenshot from 2024-10-06 12-02-41](https://github.com/user-attachments/assets/360f0c7e-06d3-4925-819a-211719df55bc)

There doesn't seem to be anything interesting in the console.

When this game used to work, it had the Heroes Lore issue of lag on input response.

**Comment by AShiningRay** [comment] 2024-10-12 17:46
This regression is likely to have been caused by zb3's queue additions on lcdui and input, and the fun part is that using queues on those is a good idea to remove race conditions, the problem is that the likelyhood of this game being terribly coded after decompiling and examining it is very high, just like Wind of Soltia which has some insane interrupt logic going on... as to how one would work around this, i've no idea yet. 

J2ME-Loader seems to be much better at this, but input and actual rendering is the kind of thing we can't just copy from them, as Android handles things differently.

**Comment by AShiningRay** [comment] 2024-12-25 23:52
Fixed by fb47eb4f98bb28fca408cf8e611108ea159f1657 while dropping a ton of lock usage throughout FreeJ2ME as well. If i deem necessary, i'll reintroduce them at a later date. But so far, nothing i tested was broken.

**Closed as completed by AShiningRay** 2024-12-25 23:52 UTC
Labels: bug
